config/routes.rb
DaBobfather::Application.routes.draw do

  match "redirect" => "redirect#index"
  
  get "sessions/create"

  resource :welcome, :only => [:index], :controller => :welcome do
    get "onboarding", :on => :collection
  end

  match 'logout' => 'sessions#destroy', :as => :logout
  match 'about' => 'welcome#about', :as => :logout
  
  resources :bobfathers

  resources :users, :except => [:index] do
    get "facebook_friends", :on => :member
  end
  
  match "admin" => "admin/users#index"
  namespace :admin do
    resources :users do
      get "facebook_friends", :on => :member
      get "start_over", :on => :collection
      
    end
  end

  match '/auth/:provider/callback' => "sessions#create"

  root :to => 'welcome#index'

end

app/controllers/bobfathers_controller.rb
class BobfathersController < ApplicationController
  def index
    @users = User.all
    # find the bobfather points
    @user = User.find_by_name("graham")
    @points = @user.incoming(:bobfather).depth(:all).count if @user
  end

  def new
  end

  def show
  end

  def create
    u1 = User.find(params[:u1])
    u2 = User.find(params[:u2])
    u1.bobfather = u2
    u1.bobfather_rel[:state] = 'proposed'
    respond_to do |format|
      if u1.save
        
        format.html { redirect_to bobfathers_path, notice: 'User was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def destroy
    u1 = User.find(params[:id])
    u2 = User.find(params[:bobfather_id])
    u1.bobfather_rel.destroy
  end

  def update
  end
end

app/helpers/bobfathers_helper.rb
module BobfathersHelper
end

app/views/bobfathers/_form.html.erb
<%= form_tag "/bobfathers" do |f| %>
  <% if @bobfather and @bobfather.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bobfather.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @bobfather.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag :bobchild %><br />
    <%= select_tag :u1, options_from_collection_for_select(User.all, :id, :name) %>
  </div>
  <div class="field">
    <%= label_tag :bobfather %><br />
    <%= select_tag :u2, options_from_collection_for_select(User.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= submit_tag "submit" %>
  </div>
<% end %>

app/views/bobfathers/create.html.erb
<h1>Bobfathers#create</h1>
<p>Find me in app/views/bobfathers/create.html.erb</p>

app/views/bobfathers/destroy.html.erb
<h1>Bobfathers#destroy</h1>
<p>Find me in app/views/bobfathers/destroy.html.erb</p>

app/views/bobfathers/index.html.erb
<h1><%= @user.name if @user %> <%= @points%></h1>

<p>
  <% @users.each do |u| %>
    <p>
      Name: <%= u.name %>
      <% if u.bobfather %>
        <br />Bobfather: <%= u.bobfather.name %> <br /> state: <%= u.bobfather_rel[:state] %><br />
      <%= link_to 'Destroy', bobfather_path(u, :bobfather_id => u.bobfather), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </p>
  <% end %>
</p>
<%= link_to 'New Bobfather Relation', new_bobfather_path %>

app/views/bobfathers/new.html.erb
<h1>New Bobfather Relation</h1>

<%= render 'form' %>

<%= link_to 'Back', bobfathers_path %>

app/views/bobfathers/show.html.erb
<h1>Bobfathers#show</h1>
<p>Find me in app/views/bobfathers/show.html.erb</p>

app/views/bobfathers/update.html.erb
<h1>Bobfathers#update</h1>
<p>Find me in app/views/bobfathers/update.html.erb</p>