config/routes.rb
DaBobfather::Application.routes.draw do

  match "redirect" => "redirect#index"
  
  get "sessions/create"

  resource :welcome, :only => [:index], :controller => :welcome do
    get "onboarding", :on => :collection
  end

  match 'logout' => 'sessions#destroy', :as => :logout
  match 'about' => 'welcome#about', :as => :logout
  
  resources :bobfathers

  resources :users, :except => [:index] do
    get "facebook_friends", :on => :member
  end
  
  match "admin" => "admin/users#index"
  namespace :admin do
    resources :users do
      get "facebook_friends", :on => :member
      get "start_over", :on => :collection
      
    end
  end

  match '/auth/:provider/callback' => "sessions#create"

  root :to => 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :node_id, :favorite_donut, :fb_access_token, :fbid, :is_bobfather, :last_login, :name, :registered, :state
  # for posting children
  attr_accessible :bobchildren, :bobfather
  
  # i essentially have my own methods for handling the logic for bobchildren
  attr_accessor :bobchildren # http://www.ruby-forum.com/topic/1748016
  
  
  after_create :create_neo
  after_update :update_neo
  before_destroy :destroy_neo

  # States of Bobfatherhood
  UNKNOWN_BOBFATHER = '0'
  I_AM_BOBFATHER = '-1'
  FEATUREALBE = "featurable"
  ## States of Relationship.  
  PROPOSED_BY_FATHER = 'proposed_by_father'
  PROPOSED_BY_CHILD = 'proposed_by_child'
  CONFIRMED = 'confirmed'
  # Relationships
  FRIENDS_REL = "friends"
  BOBFATHER_REL = "bobfather"

  LARGE_NUMBER = 10 # the "all" depth option isn't supported in many places

  def neo_con
    if $neo 
     return $neo
    else
      $neo = Neography::Rest.new
      Rails.logger.info("Neography Bug Connection Got Dropped")
    end 
  end 
  
  ##############################################################################
  # neo4J connection/access node methods
  ##############################################################################
  def neo_node_id(node)
    node_id = node["self"].split('/').last
  end
  
  def neo_end_node_id(relationship)
    node_id = relationship["end"].split('/').last
  end

  def neo_start_node_id(relationship)
    node_id = relationship["start"].split('/').last
  end
  
  def my_node
    neo_con.get_node(self.node_id)
  end
  
  def get_start_node(relationship)
    User.find_by_node_id( neo_start_node_id(relationship) )
  end

  def get_end_node(relationship)
    User.find_by_node_id( neo_end_node_id(relationship) )
  end
  
  
  ##############################################################################
  # neo4J hook mehtods
  ##############################################################################

  def create_neo    
    node = neo_con.create_node(self.attribute_names.collect {|x| [x,  self.send(x)]}.inject({}) { |r, s| r.merge!({s[0] => s[1]} ) } )
    # puts node
    # map the graph db back to the model
    my_node_id = self.neo_node_id(node)
    puts "My nodeid::#{my_node_id}"
    self.update_attributes({:node_id => my_node_id})
  end
  
  # @neo.reset_node_properties(node1, {"age" => 31})           # Reset a node's properties
  # @neo.set_node_properties(node1, {"weight" => 200})         # Set a node's properties
  def update_neo
    node = neo_con.get_node(self.node_id)
    # i'll store meta data in active record
    # updated_attr = self.attribute_names.collect {|x| [x,  self.send(x)]}.inject({}) { |r, s| r.merge!({s[0] => s[1]} ) }
    # updated_attr = updated_attr.delete_if {|k, v| v.nil?}
    # neo_con.set_node_properties(node,  updated_attr)
  end
  
  
  # @neo.delete_node(node2) # Delete an unrelated node
  # @neo.delete_node!(node2) # Delete a node and all its relationships
  def destroy_neo
    begin
      node = neo_con.get_node(self.node_id)
      neo_con.delete_node!(node)
    rescue => e
      puts e
    end
  end
  
  ##############################################################################
  # neo4J Core association methods  getters and setters
  ##############################################################################

  # Bobfather and Bobchildren

  # return nil or a User object
  def bobfather
    array_of_hashes = neo_con.get_node_relationships(self.my_node, "out", BOBFATHER_REL)
    return nil if !array_of_hashes
    raise "Can't have mulitple Bobfathers" if array_of_hashes.size > 1
    User.find_by_node_id( neo_end_node_id(array_of_hashes.first) )
  end

  # pass in either an object or id.  helpful for rails style forms
  def bobfather=(user_or_user_id)
    if user_or_user_id.class == String
      # state machine logic in here for UNKNOWN Bobfther or OUT OF NETWORK Bobfather
      self.update_bobfather(user_or_user_id)
    else
      set_bobfather(user_or_user_id)
    end  
  end
  
  def set_bobfather(user)
    # destroying old bobfather relation in neo4j to preserve uniqueness
    if self.has_bobfather?
      self.bobfather_rel_destroy
    end    
    neo_con.create_relationship(BOBFATHER_REL, self.my_node, user.my_node)
  end

  def update_bobfather(bobfather_id)
    if bobfather_id == UNKNOWN_BOBFATHER
      Rails.logger.info("User has An Out of Network Bobfather")
      # if there is a bobfather rel created
      if self.has_bobfather?
        array_of_hashes = neo_con.get_node_relationships(self.my_node, "out", BOBFATHER_REL)
        relationid =  neo_node_id(array_of_hashes.first)
        neo_con.delete_relationship(relationid) # will this work?
      end
    elsif bobfather_id == I_AM_BOBFATHER
      if self.has_bobfather?
        array_of_hashes = neo_con.get_node_relationships(self.my_node, "out", BOBFATHER_REL)
        relationid =  neo_node_id(array_of_hashes.first)
        neo_con.delete_relationship(relationid) # will this work?
      end
    elsif !bobfather_id.blank?
      u = User.find(bobfather_id)
      set_bobfather(u)
      # do state machine
      # @neo.set_relationship_properties(rel1, {"weight" => 200}) 
      # @neo.get_relationship_properties(rel1)        
      if self.has_bobfather_state? and self.bobfather_state == PROPOSED_BY_FATHER
        self.bobfather_state = CONFIRMED
      else
        self.bobfather_state = PROPOSED_BY_CHILD
      end
      save
    else
      Rails.logger.info("User has no Bobfather")
    end
  end


  # should return a relationship object/hash object
  def bobfather_rel
    array_of_hashes = neo_con.get_node_relationships(self.my_node, "out", BOBFATHER_REL)
    puts "bobfather_rel : #{array_of_hashes.first}"
    array_of_hashes.first
  end
  
  # neo_con.delete_relationship(relationid) # will this work?
  def bobfather_rel_destroy
    puts "\nabout to destory the Bobfather relationship of #{self.name}\n"
    neo_con.delete_relationship(self.bobfather_rel) # will this work?
  end


  def bobchildren
    array_of_hashes = neo_con.get_node_relationships(self.my_node, "in", BOBFATHER_REL)
    return [] if !array_of_hashes
    # Rails.logger.info("bobchildren ids::#{array_of_hashes.collect{ |x| neo_node_id(x) }}")
    User.where(:node_id => array_of_hashes.collect{ |x| neo_start_node_id(x) } )
  end

  # business logic of who gets to delete what can go here
  def update_bobchildren(bobchildren_ids)
    bobchildren_ids.reject! {|x| x.empty? }
    
    remove_bobchild_relationships(bobchildren_ids)
    # add the newly checked children
    add_bobchild_reationships(bobchildren_ids)
  end


  # remove the Unchecked Checkboxes
  def remove_bobchild_relationships(bobchildren_ids)
    existing_bobchildren_ids = bobchildren.collect {|x| x.id}
    delete_child_relaitonships = existing_bobchildren_ids - bobchildren_ids
    Rails.logger.info("\nexisting_bobchildren::#{existing_bobchildren_ids}\n")
    Rails.logger.info("\ndelete_child_relaitonships::#{delete_child_relaitonships}\n")

    delete_child_relaitonships.each do |uid|
      u = User.find(uid)
      # my new method
      u.bobfather_rel_destroy
      # u.bobfather_rel.destroy
    end
  end
  
  # State Machine Logic Applies here
  ## TOOD Refactor somewhere nice
  def add_bobchild_reationships(bobchildren_ids)
    Rails.logger.info("\n\nadding bobchildren:#{bobchildren_ids}\n\n")
    bobchildren_ids.each do |child_id|
      u = User.find(child_id)
      if u.has_bobfather?
        Rails.logger.info("\n this user has a bobfather")
        # This is A CONFIRMATION of the bobfatherhood 
        if ( (u.bobfather == self) and 
              (u.has_bobfather_state? and u.bobfather_state == PROPOSED_BY_CHILD) )
          u.bobfather_state = CONFIRMED
        end
        # if u.bobfather != self DO NOTHING b/c da child has ownship of 
        #  WHO IS MY BOBFATHER      
      else
        Rails.logger.info("\n Adding the bobfather rel")
        u.bobfather = self 
        # do state machine
        u.bobfather_state = PROPOSED_BY_FATHER
      end
      u.save
    end
  end

  # what does this return
  def bobfather_state
    neo_con.get_relationship_properties(self.bobfather_rel, ['state'])
  end

  def bobfather_state=(status)
  end
  
  

  # Friends 
  
  # make this more active record like
  def friends
    return [] if !has_friends?
    # and array of friend relationships NOT actual nodes
    array_of_hashes = neo_con.get_node_relationships(self.my_node, "out", FRIENDS_REL)
    # objects = array_of_hashes.map{|m| OpenStruct.new(m)}
    # even better, just get the full user objects
    # puts "array_of_hashes.collect{|x| x['data'']['id']}::#{array_of_hashes.collect{|x| x['data']['id']}} "
    # puts "array_of_hashes.collect{ |x| neo_node_id(x) }::#{array_of_hashes.collect{ |x| neo_node_id(x) }} "

    User.where(:node_id => array_of_hashes.collect{ |x| neo_end_node_id(x) })
  end

  # @neo.create_relationship("friends", node1, node2)          # Create a relationship between node1 and node2
  # @neo.create_unique_relationship(index_name, key, value,    # Create a unique relationship between nodes
  #                           "friends", new_node1, new_node2)   # this needs an existing index
  def add_to_friends(user)
    neo_con.create_relationship(FRIENDS_REL, self.my_node, user.my_node)
  end

  def friend_ids
    return [] if !has_friends?
    array_of_hashes = neo_con.get_node_relationships(self.my_node, "out", FRIENDS_REL)
    User.select(:id).where(:node_id => array_of_hashes.collect{ |x| neo_end_node_id(x) })
  end


  ##############################################################################
  # ? methods
  ##############################################################################
  # ex. @neo.get_node_relationships(node1, "all", "enemies")
  def has_friends?
    !!neo_con.get_node_relationships(self.my_node, "out", FRIENDS_REL) # returns nil if empty
  end


  def has_bobfather?
    self.bobfather ? true : false
  end
  

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_filter :require_login, :except => [:show]

  def facebook_friends
    @user = User.find(params[:id])
    @user.get_fb_friends
    redirect_to @user, :notice => "updated facebook friends list" and return
  end

  def start_over
    User.kill_all
    redirect_to admin_users_path, :notice => "destroyed all users"
  end


  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, :except => [:show]

  def facebook_friends
    begin
      @user = User.find(params[:id])
      @user.get_fb_friends
    rescue Timeout::Error => e
      @error = e
      #render :action => "error"
    end
    respond_to do |format|
      format.html {redirect_to edit_user_path(@user), :notice => "updated facebook friends list" and return}
      format.js {}
    end
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    # now done exactly in the setting
    # @user.update_bobfather(params[:user][:bobfather])
    @user.update_bobchildren(params[:user][:bobchildren])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row-fluid marketing">

  <h2>Who Told You About Bob's Donuts?</h2>
  </div>
  <div class="row-fluid marketing">
    <div class="span12 form-highlight">
      <p>
        <%#= @user.bobfather.id %>
      </p>
        <%= f.input :bobfather, 
            :label => "A.  Nobody told me about bobs. I discovered Bobs on my own. ",
            :collection => [[User::I_AM_BOBFATHER, "I am A Bobfather.  I discovered Bobs on my own"]], 
            :label_method => :last, 
            :value_method => :first,
            :as => :radio_buttons, 
            :item_wrapper_class => 'inline',
            :checked => true %>

          <%= f.input :bobfather, 
            :label => "B.  Select Your Bobfather from Your Friends List",
            :collection => bobfather_selection_options(@user), 
            :label_method => :last, 
            :value_method => :first,
            checked: @user.bobfather ? @user.bobfather.id : nil,
            :as => :radio_buttons, 
            :item_wrapper_class => 'inline'
             %>
          <%#= f.input :bobfather %>
          <%= f.input :bobfather, 
            :label => "C.  My Bobfather is not one of my facebook friends",
            :collection => [[User::UNKNOWN_BOBFATHER, "my bobfather is not one of my facebook friends"]], 
            :label_method => :last, 
            :value_method => :first,
            :as => :radio_buttons, 
            :item_wrapper_class => 'inline',
            :checked => true %>
    </div>
  </div>

  <hr>
  <h2>Who Did You Introduce To Bobs Donuts</h2>
  <div class="row-fluid marketing">
    <div class="span12 form-highlight">

      <p>
          <%= f.input :bobchildren, 
            :label => "Select Your Bobchildren from Your Friends List",
            :collection => bobfather_selection_options(@user), 
            :label_method => :last, 
            :value_method => :first,
            :as => :check_boxes, 
            :item_wrapper_class => 'inline',
            checked: @user.bobchildren.collect{|x| x.id} %>
      </p>
    </div>

  </div>
  <div style="text-align:center">
    <%= f.submit "Submit", :class => "btn btn-primary btn-large", :style=> ""%>
  </div>
  




<% end %>

app/views/users/_get_friends.html.erb
<div id="get_friends">
  <h2>Who Told You About Bob's Donuts?</h2>
  <p class="lead">
    Importing Your Friend List ...
    <p style="text-align:center">
      <%= image_tag("spinnerLarge.gif") %>
    </p>
  </p>
</div>
<script>
  $(document).ready(function () {
    $.ajax({
      url: "/users/<%= @user.id %>/facebook_friends.js",
      type: "GET",
    });
  });  
</script>

app/views/users/_mini_profile.html.erb
<p>
  <%= image_tag(user.fb_image_url, :class => "", :style => 'padding-right:5px')%>
  <small>
  <p>
    <% if user.bobchildren.count > 0 %>
      <%= pluralize user.bobchildren.count,  'Bobchild' %> 
    <% end %>
  </p>
  </small>
</p>
<p>
  <%= link_to user.name, user_path(user) %>
</p>

app/views/users/_profile.html.erb
<p>
  <%= image_tag(user.fb_image_url(:large), :class => "", :style => 'padding-right:5px')%>
  <small>
  <p>
    <% if user.lineage_total > 0 %>
      <%= user.lineage_total %> Bob's Progeny
    <% end %>
  </p>
  <p>
    <% if user.bobchildren.count > 0 %>
      <%= pluralize user.bobchildren.count,  'Bobchild' %> 
    <% end %>
  </p>
  </small>
</p>
<p>
  <%= link_to name_helper(user), user_path(user) %>
</p>

app/views/users/edit.html.erb
<% if @user.has_friends? %>
  <%= render 'users/form' %>
<% else %>
  <%= render 'users/get_friends' %>  
<% end %>

<p style ="margin:50px 0">
<%= link_to "Import Friends From Facebook", 
  facebook_friends_user_path(@user) %>
</p>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Fbid</th>
    <th>Registered</th>
    <th>Fb access token</th>
    <th>Favorite donut</th>
    <th>Last login</th>
    <th>State</th>
    <th>Is bobfather</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.fbid %></td>
    <td><%= user.registered %></td>
    <td><%= user.fb_access_token %></td>
    <td><%= user.favorite_donut %></td>
    <td><%= user.last_login %></td>
    <td><%= user.state %></td>
    <td><%= user.is_bobfather %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<hr>

<div class="jumbotron">
  <p>
    <%= image_tag(@user.fb_image_url('large') ) %>
  </p>
  <p>
    <h1><%= @user.name %></h1>

  </p>
  <p>
    <% if @user.lineage_total > 0 %>
      <%= @user.lineage_total %> Bob's Progeny
    <% end %>
  </p>
  <p>
    <% if @user.bobchildren.count > 0 %>
      <%= @user.bobchildren.count %> bobchildren
    <% end %>
  </p>

  <p>

    <div id="fb-root"></div>
    <script src="http://connect.facebook.net/en_US/all.js"></script>
    <script>
      FB.init({
        appId  : '529867487070709',
        status : true, // check login status
        cookie : true, // enable cookies to allow the server to access the session
        xfbml  : true  // parse XFBML
      });
    </script>
    <script>
    
    
    function sendRequestToRecipients() {
      msg = ' has indicated you share a love for Bobs Donuts.  Explore your Bobs Ancestry'
      FB.ui({method: 'apprequests',
        message: msg,
        to: '<%= @user.fbid %>'
      });
    }
    </script>
    <% if !@user.registered? %>
    <b> <%= @user.name %> has not signed up yet.  <%= link_to_function("Invite #{@user.name}", "sendRequestToRecipients();") %></b>
    <% end %>
  </p>
  <p>
    <%= render :partial => "shared/relationship" %>
  </p>

  
</div>
<div class="row-fluid marketing">
  <div class="span6">
    <p class="lead"><%= possesive_helper(@user) %> Bobfather</p>

    <p>
      <% if @user.bobfather %>
        <%= render :partial => "users/mini_profile", 
        :locals => {:user => @user.bobfather}%>
      <% else %>
        <%= @user.bobfather_status %>
      <% end %>
    </p>
  </div>
  <div class="span6">
    <p class="lead">Bobfather of <%= possesive_helper(@user) %> Lineage</p>
    <p>
      <% if @user.bobfather %>
        <%= render :partial => "users/mini_profile", 
        :locals => {:user => @user.don_bobfather} %>
      <% else %>
        <%= @user.bobfather_status %>
      <% end %>
    </p>
  </div>
</div>

<hr>
<p class="lead"><%= possesive_helper(@user) %> Bobchildren</p>

<div class="row">
  <% if @user.has_bobchildren? %>
    <% @user.bobchildren.each do |user| %>
      <div class="span3">
        <%= render :partial => "users/mini_profile", 
        :locals => {:user => user}%>
      </div>
    <% end %>
  <% else %>
    This User has no Bobchildren.  His/Her Lineage Stops here
  <% end %>
</div>
<hr>



<%#= link_to 'Back', users_path %>